### ISSUE TITLE
eraseToAnyView when building for release

### ISSUE THREAD

**Issue by spnkr** [johnno1962/HotSwiftUI#2]
In the readme it says that it's safe to keep `.eraseToAnyView()` in your release app code.

I see in the source that, in release mode, `eraseToAnyView()` is this:

```
public func eraseToAnyView() -> some SwiftUI.View { return self }
```

Question: are there any implications of erasing the type of the view? Also am I right in saying that the type is being erased?

**Comment by johnno1962** [comment]
Hi @spnkr, not sure I follow you. The code you list should be a no-op/transparent. It's only in a debug compile the AnyView initialiser is used to wrap the concrete type which is needed if you want to inject interface changes.

**Comment by johnno1962** [comment]
@spnkr, I don't know if you've noticed but there is a new version of Injection on the block. You may want to try it out is it should be a little faster/more reliable/simpler to use and is likely the future.

https://github.com/johnno1962/InjectionNext
