### ISSUE TITLE
Code appears to be injected but view doesn't refresh

### ISSUE THREAD

**Issue by cerupcat** [johnno1962/HotSwiftUI#3]
I'm using the latest version [1.1.8](https://github.com/johnno1962/HotSwiftUI/releases/tag/1.1.8), 5.0.0 Xcode 15.3, xrOS, device and TCA injection https://github.com/johnno1962/InjectionIII/releases/tag/5.0.0, and Xcode 15.3.

Everything properly connects and correct lists file updates. 

💉 Injected type #1 '....'

However, the visuals of the view are never updated in the simulator. It's unclear if this is an issue with HotSwiftUI or InjectionIII.

**Comment by johnno1962** [comment]
Do you have an @ObserveInjection property wrapper var in the view?

**Comment by cerupcat** [comment]
Yes,I have:`@ObserveInjection var forceRedraw` in the view. The view does appear to refresh, but doesn't include the code changes. For example, if I set a random color for a view, the view does change color when saving file changes. However, the actual changes aren't applied (eg. changing size or adding new views).

The very first time I save a file, I get the following warning which I imagine could be related. Subsequent saves do not produce this warning (but also don't show view updates).

```💉 ⚠️ Injection may have failed. Have you added -Xlinker -interposable (without double quotes and on separate lines) to the "Other Linker Flags" of the executable and frameworks? ⚠️```

However, I do have linker flags setup.

<img width="514" alt="Screenshot 2024-05-09 at 5 42 45 PM" src="https://github.com/johnno1962/HotSwiftUI/assets/204151/76041209-2af3-47bb-a4b8-47e7785a8add">

I'm not sure if it matters, but we also configure Xcode using Package.swift. Our app is modular and uses a number of modules throughout. I've included the linker flags in each module too, but that doesn't appear to help remove the warning.

```
extension [SwiftSetting] {
    static let common: Self = [
        .unsafeFlags(["-Xlinker", "-interposable"]),
            .when(configuration: .debug)),
    ]
}```

**Comment by johnno1962** [comment]
You'll have to sort out the problem with your linker flags for display update to work. That error message means the new version of your View body function has not "interposed" (something like swizzling).

**Comment by cerupcat** [comment]
> You'll have to sort out the problem with your linker flags for display update to work. That error message means the new version of your View body function has not "interposed" (something like swizzling).

Are there any limitations in terms of using many modules in a project? We essentially have a fully modularized project with about 100 modules that get built into a single dynamic framework and then they get added to our main project. From what I can tell, the linker flags are properly set (I see them in the build log), so it's unclear what's missing.

**Comment by cerupcat** [comment]
I found the issue. I was using `swiftSettings` instead of `linkerSettings` when setting the flags in Package.swift. Everything is working now.
